### ISSUE TITLE
expose msync

### ISSUE THREAD

**Issue by jasonhe88** [calcinai/php-ext-mmap#1]
Thank you for your great work, this is exactly what I am looking for!

In my project, I need to write dirty data into file right after data change. my understanding is that flush will write whole file.  Could you please expose the msync function as well?

just like：

$mmap = mmap_open($file_name, $block_size, $offset);
mmap_msync( $mmap, $addr, $length, ASYNC | SYNC );

 or some other format.

Thanks!!!

Jason

**Comment by calcinai** [comment]
I'll have a look at it later this week if that's ok.  Otherwise, feel free to make a PR with the change.

**Comment by calcinai** [comment]
Hey, sorry I've just got on to this.  Are you unable to flush/sync it with php's `fflush()`?

**Comment by jasonhe88** [comment]
I am not sure if php's fflush can do the same thing as mmap_msync do.  will give it a try. thanks!

**Comment by calcinai** [comment]
If you take a look at the stream implementation you'll see that the `fflush()` is just wrapping `msync()` anyway.

**Comment by jasonhe88** [comment]
from the parameters of mmap_msync, I assume mmap_msync can write a piece of data with starting position and length into file. For fflush, from my understanding, it writes all data into file, is that right?

**Comment by calcinai** [comment]
The code is [here](https://github.com/calcinai/php-ext-mmap/blob/master/mmap.c#L81) - it will write out the mapped portion (not the whole file) when you call `fflush()` on the handle

**Comment by jasonhe88** [comment]
cool! thank you!

i don't have much ideas on how to write a php extension in C. This extension helps a lot!

**Comment by calcinai** [comment]
No problem
